# Debian, miniconda, ESRIN-Sen2Cor Dockerfile
# https://github.com/edwardpmorris/docker-snap
# sen2cor from http://step.esa.int/main/third-party-plugins-2/sen2cor/

# pull base image (use a specific version tag ':tag')
FROM  continuumio/miniconda:4.0.5

# maintainer details
MAINTAINER epmorris "edward.morris@uca.es"

# update version labels
LABEL sen2cor_version='2.2.1' 
ENV SEN2COR_VERSION '2.2.1'

# install conda packages (sen2cor setup.py expects anaconda)
RUN conda install --yes \
    pytables \
    psutil \
    scipy \
    scikit-image

# create user group
RUN groupadd -r worker \
    && useradd -r -m -g worker worker

# set work directory to home give worker full ownership of all files in $HOME
ENV  HOME /home/worker
WORKDIR $HOME
#RUN chown -R worker:worker $HOME

# download, check, extract and clean up sen2cor from step.esa.int
# FIXME: improve verification, https://github.com/docker-library/official-images
# FIXME: https not available
ENV SEN2COR_DOWNLOAD_SHA256 81ac7bd389bdce6a24f780d067fbf89324fc6ac314c9d9c28da55d414d1e7d3e
RUN curl -fSL -o sen2cor-${SEN2COR_VERSION}.tar.gz "http://step.esa.int/thirdparties/sen2cor/${SEN2COR_VERSION}/sen2cor-${SEN2COR_VERSION}.tar.gz" \
    && echo "$SEN2COR_DOWNLOAD_SHA256 *sen2cor-${SEN2COR_VERSION}.tar.gz" | sha256sum -c - \
    && tar -xvzf sen2cor-${SEN2COR_VERSION}.tar.gz \
    && rm sen2cor-${SEN2COR_VERSION}.tar.gz

# add headless setup (interactive prompts commented, use defaut path options)
# FIXME: check if a 'default settings' flag exists for setup.py
COPY setup.py $HOME/sen2cor-${SEN2COR_VERSION}

# install sen2cor    
RUN cd sen2cor-2.2.1 && \
    python setup.py install --quiet
    
# update environment variables (paths generated by setup.py)
# FIXME: this cmd does not seem to set env variables 
# as in they are not set when starting a new container
RUN /bin/bash /home/worker/sen2cor/L2A_Bashrc

# set by looking at default instalation    
# FIXME: these should be auto generated
ENV  GDAL_DATA /opt/conda/lib/python2.7/site-packages/sen2cor-2.2.1-py2.7.egg/sen2cor/cfg/gdal_data
ENV  SEN2COR_BIN /opt/conda/lib/python2.7/site-packages/sen2cor-2.2.1-py2.7.egg/sen2cor
ENV  SEN2COR_HOME $HOME/sen2cor

# copy adjusted L2A configuration
# FIXME: makes an option to replace when starting the container
# see L2A_Process option --GIP_L2A GIP_L2A
#RUN cp -r $SEN2COR_BIN/cfg/ $SEN2COR_HOME
COPY L2A_GIPP.xml $SEN2COR_HOME/cfg

# warning! runs as root until permission issues resolved
# http://forum.step.esa.int/t/sen2cor-writes-files-in-the-installation-folder-at-runtime/2013
#RUN chown -R worker:worker /opt/conda/lib/python2.7/site-packages/sen2cor-2.2.1-py2.7.egg/sen2cor/cfg
#RUN cp $SEN2COR_BIN/cfg/L2A_CAL_AC_GIPP.xml $SEN2COR_HOME/cfg \
#    && cp $SEN2COR_BIN/cfg/L2A_CAL_SC_GIPP.xml $SEN2COR_HOME/cfg
ENV PATH $SEN2COR_BIN:$PATH
RUN chmod 755 $SEN2COR_BIN
RUN chown -R worker:worker $HOME
USER worker