# Debian, miniconda, ESRIN-Sen2Cor Dockerfile
# https://github.com/edwardpmorris/docker-snap
# sen2cor from http://step.esa.int/main/third-party-plugins-2/sen2cor/

# pull base image (use a specific version tag ':tag')
FROM debian:8

# maintainer details
MAINTAINER epmorris "edward.morris@uca.es"

# update image labels
LABEL sen2cor_version='2.2.1' 

# miniconda INSTALL
# update and install packages
RUN apt-get update --fix-missing && apt-get install -y wget bzip2 ca-certificates \
    libglib2.0-0 libxext6 libsm6 libxrender1 \
    git mercurial subversion

# install miniconda
RUN echo 'export PATH=/opt/conda/bin:$PATH' > /etc/profile.d/conda.sh && \
    wget --quiet https://repo.continuum.io/miniconda/Miniconda2-4.0.5-Linux-x86_64.sh && \
    /bin/bash /Miniconda2-4.0.5-Linux-x86_64.sh -b -p /opt/conda && \
    rm Miniconda2-4.0.5-Linux-x86_64.sh

ENV PATH /opt/conda/bin:$PATH

# http://bugs.python.org/issue19846
# At the moment, setting "LANG=C" on a Linux system *fundamentally breaks Python 3*, and that's not OK.
ENV LANG C.UTF-8

# install conda packages
RUN conda install --yes \
    pytables \
    psutil \
    scipy \
    scikit-image

# CHECK IF NEEDED
# install libopenjp2
#RUN apt-get update -y && apt-get install -y \ 
#      libopenjp2-7 \
#    && rm -fr /var/lib/apt/lists/*

# create user group
RUN groupadd -r worker \
    && useradd -r -g worker worker

# set work directory to home
ENV  HOME /home/worker
WORKDIR $HOME

# get sen2cor from step.esa
RUN wget --quiet http://step.esa.int/thirdparties/sen2cor/2.2.1/sen2cor-2.2.1.tar.gz && \
    tar -xvzf sen2cor-2.2.1.tar.gz && \
    rm sen2cor-2.2.1.tar.gz

# add headless setup (interactive prompts commented, defaut options) 
COPY setup.py $HOME/sen2cor-2.2.1

# install sen2cor    
RUN cd sen2cor-2.2.1 && \
    python setup.py install --quiet
    
# update environment variables (paths generated by setup.py)
# FIXME: this cmd does not seem to set env variables
RUN cd /home/worker/sen2cor && \
    /bin/bash ./L2A_Bashrc
# set by looking at default instalation    
ENV  GDAL_DATA /opt/conda/lib/python2.7/site-packages/sen2cor-2.2.1-py2.7.egg/sen2cor/cfg/gdal_data
ENV  SEN2COR_BIN /opt/conda/lib/python2.7/site-packages/sen2cor-2.2.1-py2.7.egg/sen2cor
ENV  SEN2COR_HOME $HOME/sen2cor

# copy adjusted L2A configuration (FIXME: makes this more dynamic)
COPY L2A_GIPP.xml $SEN2COR_HOME/cfg 

# give worker full ownership of all files in $HOME
RUN chown -R worker:worker $HOME

# warning! runs as root until permission issues resolved
#RUN chown -R worker:worker /opt/conda/lib/python2.7/site-packages/sen2cor-2.2.1-py2.7.egg/sen2cor/cfg
#USER worker